# -*- coding: utf-8 -*-
"""Build_PGx_Rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dvbis6Ssmj7KQAWEbBSb6hoi4UMs6sFx
"""

# Spark session (start distributed processing)
spark = SparkSession.builder.appName("merge_gene_testalert_inner_restartable").getOrCreate()

# Load large datasets
gene_df  = spark.read.options(**csv_opts).csv(GENE_CSV)
alert_df = spark.read.options(**csv_opts).csv(ALERT_CSV)

# Normalize join keys (clean + standardize matching columns)
gene_df  = gene_df.withColumn("__jkey", norm("symbol"))
alert_df = alert_df.withColumn("__jkey", norm("genesymbol"))

# Remove unnecessary/conflicting columns
for c in ["activityvalue1", "activityvalue2", "id_x", "id_y"]:
    if c in gene_df.columns:  gene_df  = gene_df.drop(c)
    if c in alert_df.columns: alert_df = alert_df.drop(c)

# Rename overlapping columns (avoid overwrite)
conflict_cols = ["name", "lookupkey", "activityscore", "population", "allelestatus", "genes"]
for c in conflict_cols:
    if c in alert_df.columns:
        alert_df = alert_df.withColumnRenamed(c, f"{c}_alert")

# Bucket-based partitioning (scalable processing)
mod = (F.abs(F.hash(F.col("__jkey"))) % F.lit(N_BUCKETS))
g_b = gene_df.filter(mod == F.lit(b))
a_b = alert_df.filter(mod == F.lit(b))

# Core join operation (main merge logic)
merged_b = g_b.join(a_b, on="__jkey", how="inner")

# Resolve duplicate columns (combine information safely)
for c in conflict_cols:
    alt = f"{c}_alert"
    if c in merged_b.columns and alt in merged_b.columns:
        merged_b = merged_b.withColumn(c, F.coalesce(F.col(c), F.col(alt))).drop(alt)

# Restartable process (skip completed buckets)
if not must_run and bucket_has_parquet(bucket_path):
    return

# Save per-bucket output (efficient storage)
merged_b.coalesce(1).write.mode("overwrite").parquet(bucket_path)

# Process all buckets (full dataset execution)
for b in buckets:
    write_bucket(b)

# Read final merged dataset
merged_all = spark.read.parquet(OUTDIR)

# Generate small sample for verification
merged_all.limit(100).coalesce(1).write.mode("overwrite").option("header", "true").csv(SAMPLE)

# Print dataset size (proof of scale)
print("gene rows:", gene_df.count())
print("alert rows:", alert_df.count())