# -*- coding: utf-8 -*-
"""Finetune_LLama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dvbis6Ssmj7KQAWEbBSb6hoi4UMs6sFx
"""

# base model configuration (LLM used for fine-tuning)
BASE_MODEL = "meta-llama/Meta-Llama-3.1-8B-Instruct"

# training and validation datasets
TRAIN_FILE = "/project/6093227/parafin1/eval_splits/train.jsonl"
DEV_FILE   = "/project/6093227/parafin1/eval_splits/dev.jsonl"

# sequence length (controls context size)
MAX_LENGTH = 2048

# LoRA hyperparameters (parameter-efficient fine-tuning)
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05

# target modules for LoRA (attention + feed-forward layers)
TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

# training configuration (controls optimization)
LEARNING_RATE = 1e-5
MAX_STEPS = 1000
WARMUP_STEPS = 50
PER_DEVICE_BATCH = 1
GRAD_ACCUM = 8

# prompt construction (instruction + input formatting)
def build_prompt(j):
    return "### Instruction:\n... \n### Input:\n" + flatten_row_text(j) + "\n### Answer:\n"

# extract best clinical recommendation (label generation)
def extract_best_answer_from_row(j):
    # selects most relevant recommendation-like text
    return best_candidate_text

# load dataset and build training samples
train_data = load_jsonl(TRAIN_FILE)
dev_data   = load_jsonl(DEV_FILE)

# tokenizer setup (text → tokens)
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token

# custom dataset (train only on answer part)
train_dataset = AnswerOnlyDataset(train_texts, tokenizer, max_length=MAX_LENGTH)
eval_dataset  = AnswerOnlyDataset(dev_texts, tokenizer, max_length=MAX_LENGTH)

# load base LLM model
model = AutoModelForCausalLM.from_pretrained(BASE_MODEL, device_map="auto")

# apply LoRA (reduce trainable parameters)
lora_config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=TARGET_MODULES,
)
model = get_peft_model(model, lora_config)

# training arguments (optimization + checkpointing)
training_args = TrainingArguments(
    output_dir="./lora_output_llama",
    per_device_train_batch_size=PER_DEVICE_BATCH,
    gradient_accumulation_steps=GRAD_ACCUM,
    learning_rate=LEARNING_RATE,
    max_steps=MAX_STEPS,
)

# trainer setup (training pipeline)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
)

# resume training if checkpoint exists
trainer.train(resume_from_checkpoint=latest_ckpt if latest_ckpt else None)

# save final LoRA adapter (trained weights)
model.save_pretrained("my_llama3_1_8b_lora")
tokenizer.save_pretrained("my_llama3_1_8b_lora")