# -*- coding: utf-8 -*-
"""pgx_hybrid_rag_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dvbis6Ssmj7KQAWEbBSb6hoi4UMs6sFx
"""

# dataset paths (RAG sources)
BIG_JSONL = "/project/6093227/parafin1/build_pgx_rag.jsonl"
GUIDE_JSONL = "/project/6093227/parafin1/chunks.jsonl"

# base model + LoRA adapter
BASE_MODEL = "Qwen/Qwen3-8B"
ADAPTER_DIR = "/project/6093227/parafin1/my_qwen3_8b_lora"

# retrieval settings (control number of evidence)
TOPK_BIG = 3
TOPK_GUIDE = 2

# load reranker model (semantic similarity)
reranker = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# load tokenizer and base LLM
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
base_model = AutoModelForCausalLM.from_pretrained(BASE_MODEL, device_map="auto")

# load and merge LoRA adapter (fine-tuned weights)
model = PeftModel.from_pretrained(base_model, ADAPTER_DIR)
model = model.merge_and_unload()
model.eval()

# extract gene and allele from query (entity extraction)
def extract_entities(text):
    gene = ...
    allele = ...
    return gene, allele

# keyword-based retrieval (fast filtering)
def grep_candidates(path, gene="", drug="", allele=""):
    return matched_rows

# retrieve candidate rows from dataset
def get_big_rows(gene="", drug="", allele=""):
    return rows

# semantic re-ranking (select most relevant evidence)
def score_rows(query, rows, topk):
    return topk_rows

# guideline retrieval (secondary knowledge source)
def score_guidelines(query, topk):
    return top_guidelines

# clean retrieved evidence (remove noise)
def clean_evidence(text):
    return cleaned_text

# build prompt with evidence (RAG core logic)
def build_prompt(question, big_hits, guide_hits):
    return formatted_prompt

# generate final answer using LLM
def generate_answer(prompt):
    output = model.generate(...)
    return final_answer

# main pipeline (query → retrieve → rank → generate)
def answer_question(question, gene_manual, drug_manual, allele_manual):
    big_rows = get_big_rows(...)
    big_hits = score_rows(...)
    guide_hits = score_guidelines(...)
    prompt = build_prompt(...)
    answer = generate_answer(prompt)
    return answer

# user interface (Gradio app)
demo = gr.Interface(
    fn=answer_question,
    inputs=[...],
    outputs=[...],
)

demo.launch()